### ISSUE TITLE
dotnet core test is not running on Windows plateform

### ISSUE THREAD

**Issue by bastiflew** [emilybache/GildedRose-Refactoring-Kata#119]
Hello,

There's an issue in the dotnet core test on Windows only (I guess), for some reasons the console stdout is changing the carriage return sequence, and the test can't be validated.

**Comment by emilybache** [comment]
I fixed this by updating the test to use the Approvals framework. The test still fails, but the idea is that to fix it you have to learn about the Approvals framework.

**Comment by rdammkoehler** [comment]
Not thrilled that I need to learn the Approvals test framework at the moment as I'm evaluating someone and neither of us know why the test fails, even after reading the docs. I guess if I wanted to learn Approval test framework I'd go to their website. I do appreciate that you maintain this repo but I don't think the 'test framework doesn't work' is helpful since it works in all the other repos AFIK.

**Comment by emilybache** [comment]
There is no need for you to learn the Approvals framework to do this exercise. There is a failing unit test that doesn't use Approvals that you can start from instead. You can write your own tests, that is a perfectly valid way to use this exercise.
