### ISSUE TITLE
texttest quality values for Conjured Mana Cake incorrect

### ISSUE THREAD

**Issue by marshalltower** [emilybache/GildedRose-Refactoring-Kata#175]
Based on the requirements
- "Conjured" items degrade in Quality twice as fast as normal items

**Comment by emilybache** [comment]
yes that's right.

**Comment by marshalltower** [comment]
Perhaps the requirements need to be clarified that conjured items degrade in twice twice as fast as normal items, once the sell by date has passed. 

Currently they degrade at the same rate as normal if above the sell by date.

**Comment by emilybache** [comment]
yes. This is an exercise left for you to fix.

**Comment by marshalltower** [comment]
Sorry I believe you're missing the details. I'm well away of the point of the exercise; however, either the data that your are providing as test data to test against in texttest is either incorrect or the requirements could use some clarity. I will outline the issues below:

- The requirements indicate that normal items degrade at rate of 1 which doubles to 2 once the sell by date is past.
- The requirements also indicate that the conjured items degrade at twice the rate of normal items. This can be construed two ways:
1.  Conjured items degrade at a rate of 2 which double to 4 once the sell by date is past (i.e how i interrupted it)
2.  Conjured items degrade at a rate of 1 which and then 4 once the sell by is past (at double normal degrade rate of normal once past the sell by date).
3. The current texttest values for conjured items degrade at 1 (same as normal) which doubles to 2 (as a normal) once the sell by date is past.

The only other way I can interpret your response "This is an exercise left for you to fix" would be that the texttest themselves are also incorrect and need refactoring/correcting; which gives conflicting thoughts even that people which be using the texttest to compare whether or not their solutions are functional.

**Comment by emilybache** [comment]
The current texttests reflect the current behaviour of the system. That is by design, it is not a mistake. The tests are intended as an aid to refactoring, not as an aid to implementing the new feature. They are not a requirements document. Requirements are provided only as a plain text description of what the owner of the fictional inn would like, as you have quoted. 

When you do this exercise, the first thing to do is to refactor. For that you need green tests. Once you have done refactoring, then you can go on to add the new feature. These are separate activities, I read in your question that you have conflated them. With an approval test it is essential to know whether you are refactoring or whether you are adding a new feature. Once you have added support for conjured items you will no doubt want to approve a new version of the texttest output with updated values for conjured items. This is how approval testing works. 

It is meaningless to say 'the texttest themselves are incorrect and need refactoring/correcting'. Approval testing means 'this is what I approve today, this is how the system works. I may approve something different tomorrow when we have new requirements'. Approval testing does not say 'this is correct for all time and forever'.

I hope that clarifies the situation and why the texttests are perfectly fine as they are, a starting point for this exercise.
