### ISSUE TITLE
[elixir] Is this one correctly implemented?

### ISSUE THREAD

**Issue by NobbZ** [emilybache/GildedRose-Refactoring-Kata#34]
I wanted to tackle this kata as I heard so much about it and was happy that there is an elixir version available in this repositoriy.

So I thought, "lets start with that failing test!" – Nope… No failing tests, only a single one which is empty, it does test even less than an asserting `true`…

So move on… Just write tests… 

First one was that an items quality is reduced by 1, check! worked well…
Second one was to check if `sell_in` of an item is decremented, and guess… It is not. So I took a look into the corresponding source and found out, that there is only reading access to that field, but no writing access. So I took a look at the ruby sources, which in fact do update that field/attribute, so missing it seems not to be on purpose.

Maybe there are other flaws I haven't found so far…

**Comment by emilybache** [comment]
Oh dear! I'm sorry to hear that. I'm afraid I don't know elixir myself so I totally relied on the person who sent me a pull request with the translation. It should do the same as the Ruby version, of course, and sell_in should be decremented. 

So do you think you can fix it and send me a new pull request? Or would it be better if I were to remove the elixir version from the repo since it doesn't work?

Emily

**Comment by NobbZ** [comment]
I'm crawling through the haskell version right now to get an overview over the katas starting point and I've planned to update and PR elixir after that ;) Maybe it takes a week or two, there is much going on currently…

**Comment by robphoenix** [comment]
Is this closed by #47?

**Comment by emilybache** [comment]
could well be, Rob, I think I should close it anyway since it's quite old
